//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librería.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class autor
    {
        public int idAutor { get; set; }
        public string nombreAutor { get; set; }
        public string apellidoAutor { get; set; }
        public string estado { get; set; }
        public Nullable<int> edad { get; set; }
        public string pais { get; set; }
    }
}
