//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librería.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class editorial
    {
        public int idEditorial { get; set; }
        public string nombreEditorial { get; set; }
        public string direccionEditorial { get; set; }
        public string descripcion { get; set; }
        public string telefono { get; set; }
    }
}
