//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librería.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibrosProyectoEntities : DbContext
    {
        public LibrosProyectoEntities()
            : base("name=LibrosProyectoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autor> autor { get; set; }
        public virtual DbSet<editorial> editorial { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<facturaDetalle> facturaDetalle { get; set; }
        public virtual DbSet<libros> libros { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
