//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librería.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class libros
    {
        public int idLibros { get; set; }
        public string nombreLibro { get; set; }
        public Nullable<System.DateTime> fechaPublicacion { get; set; }
        public Nullable<decimal> precioLibro { get; set; }
        public Nullable<int> idEditorial { get; set; }
        public Nullable<int> idAutor { get; set; }
    }
}
