//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librería.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int idUsario { get; set; }
        public string userName { get; set; }
        public string pswrd { get; set; }
        public string nombreDelUsuario { get; set; }
    }
}
